auto: true
pygments: true
paginate: 10
description: Website, Blog and portfolio of Chris Mousdale a designer and developer living in Jersey, Channel Islands
keywords: Chris Mousdale, web design Jersey, web designer jersey, mousdale, design blog, web design blog, photography, html5, css3