highlighter: pygments
description: Chris Mousdale is a digital creative, specilaising in web design, branding and web development for Wordpress and Shopify living in Jersey, Channel Islands.
analytics: UA-15920114-1
permalink: /blog/:categories/:year/:month/:day/:title.html
url: "http://www.mousdale.com"
excerpt_separator: "\n\n"
